# Generated by Django 3.1.3 on 2021-02-09 17:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='databaseForBlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', tinymce.models.HTMLField()),
                ('img_height', models.PositiveBigIntegerField(blank=True, null=True)),
                ('img_width', models.PositiveBigIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_for_blogs/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='databaseForCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_coordinates', models.CharField(max_length=500)),
                ('name_of_locations', models.CharField(max_length=300)),
                ('adresse', models.CharField(max_length=300)),
                ('code_postal', models.CharField(max_length=300)),
                ('localite', models.CharField(max_length=300)),
                ('informations_supplementaires', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='databaseForNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='test@gmail.com', max_length=254)),
            ],
        ),
    ]
